basePath: /
definitions:
  dto.Health:
    properties:
      environment:
        type: string
      time:
        type: string
      up:
        type: boolean
    type: object
  dto.UrlRecord:
    properties:
      expiration:
        type: string
      url:
        type: string
    type: object
host: localhost:8081
info:
  contact:
    email: suporte@swagger.io
    url: http://www.swagger.io/support
  description: Shortener api
  termsOfService: http://swagger.io/terms/
  title: Shortify
paths:
  /{id}:
    get:
      description: Busca um registro de URL no banco de dados
      parameters:
      - description: ID da URL
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "307":
          description: Success
          schema:
            $ref: '#/definitions/dto.UrlRecord'
        "404":
          description: URL não encontrada
          schema:
            type: string
      summary: Get URL
  /health:
    get:
      description: Check up app
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/dto.Health'
      summary: Get Health
swagger: "2.0"
